# Generated by Django 3.2.9 on 2021-12-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_monoid_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monoid',
            name='mono_id',
            field=models.CharField(max_length=100),
        ),
    ]
