# Generated by Django 3.2.9 on 2021-12-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sendstatement_statementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendstatement',
            name='reason',
            field=models.CharField(default='OmO', max_length=250),
            preserve_default=False,
        ),
    ]
